export const actionTypes = {
    // SET MONTH INDEX - CURRENT
    SET_MONTH_INDEX : "SET_MONTH_INDEX",
    SET_DAY_SELECTED: "SET_DAY_SELECTED",
    // OPEN AND CLOSE CALENDAR
    OPEN_EVENT_CALENDAR: "OPEN_EVENT_CALENDAR",
    CLOSE_EVENT_CALENDAR: "CLOSE_EVENT_CALENDAR",
}